version: "2"
services:
  elasticsearch:
    image: elasticsearch:2.3.3
    command: elasticsearch
  kibana:
    image: kibana:4.5.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:2.3.2
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash:/etc/logstash/conf.d
    depends_on:
      - elasticsearch
  filebeat:
    image: prima/filebeat
    volumes:
      - ./filebeat/filebeat.yml:/filebeat.yml
      - ./fake-logs:/fake/logs
    depends_on:
      - logstash
